# Use the official Node.js image as the base image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the application code
COPY . .

# Build the project
RUN npm run build

# Expose the port Nest.js will run on
EXPOSE 3000

# Command to run the app
CMD ["node", "dist/main.js"]
